apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tf-system
resources:
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/crds/tf.isaaguilar.com_terraforms_crd.yaml
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/operator.yaml
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/role.yaml
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/role_binding.yaml
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/service_account.yaml
- namespace.yaml

images:
- name: isaaguilar/terraform-operator
  newTag: v0.3.9
