apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/operator.yaml
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/role.yaml
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/role_binding.yaml
- https://raw.githubusercontent.com/isaaguilar/terraform-operator/v0.3.9/deploy/service_account.yaml
