apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

crds:
- tf.isaaguilar.com_terraforms_crd.yaml
resources:
- namespace.yaml
- https://github.com/isaaguilar/terraform-operator//deploy/operator.yaml?ref=v0.3.8
- https://github.com/isaaguilar/terraform-operator//deploy/role.yaml?ref=v0.3.8
- https://github.com/isaaguilar/terraform-operator//deploy/role_binding.yaml?ref=v0.3.8
- https://github.com/isaaguilar/terraform-operator//deploy/service_account.yaml?ref=v0.3.8