---
# Source: terraform-operator/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-operator
  labels:
    app: terraform-operator
    chart: terraform-operator-v0.1.15
    release: terraform-operator
    heritage: Helm
---
# Source: terraform-operator/templates/controller-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-operator
  labels:
    app: terraform-operator
    chart: terraform-operator-v0.1.15
    release: terraform-operator
    heritage: Helm
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  - nodes
  verbs:
  - '*'

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'

- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'

- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'

- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create

- apiGroups:
  - apps
  resourceNames:
  - terraform-operator
  resources:
  - deployments/finalizers
  verbs:
  - update

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get

- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get

- apiGroups:
  - tf.isaaguilar.com
  resources:
  - '*'
  verbs:
  - '*'
---
# Source: terraform-operator/templates/controller-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terraform-operator
  labels:
    app: terraform-operator
    chart: terraform-operator-v0.1.15
    release: terraform-operator
    heritage: Helm
subjects:
- kind: ServiceAccount
  name: terraform-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: terraform-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: terraform-operator/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-operator
  labels:
    app: terraform-operator
    chart: terraform-operator-v0.1.15
    release: terraform-operator
    heritage: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: terraform-operator
      release: terraform-operator
  template:
    metadata:
      labels:
        app: terraform-operator
        release: terraform-operator
    spec:
      serviceAccountName: terraform-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: terraform-operator
        image: "isaaguilar/terraform-operator:v0.3.8"
        imagePullPolicy: Always
        command:
        - terraform-operator
        args:
        - --zap-log-level=debug
        - --zap-encoder=console
        env:
        - name: WATCH_NAMESPACE # Leave blank to watch all namespaces
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: terraform-operator
        resources:
          limits:
            cpu: 50m
            memory: 128M
          requests:
            cpu: 25m
            memory: 64M
